version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    env_file:
      - ./.env
    # networks:
    #    - rabbitmq_go_net

  redis:
    container_name: shop_project_redis
    image: redis:latest
    restart: always
    healthcheck:
      test: redis-cli ping
      timeout: 45s
      interval: 10s
      retries: 10
    env_file:
      - ./.env

  celery:
    container_name: shop_project_celery_worker
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    command: worker
    env_file:
      - ./.env

  shop:
    container_name: shop_project_django
    build:
      dockerfile: dockerfiles/Dockerfile
      context: .
    command: server
    stdin_open: true
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ./:/app
    ports:
      - "84:84"
    env_file:
      - ./.env

volumes:
  rabbitmq_data:
  rabbitmq_log:
