# Generated by Django 4.1.2 on 2022-10-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="qualtity",
            new_name="quantity",
        ),
    ]
